{{- if not .Values.auth.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "etcd.fullname" . }}-root
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
type: Opaque
data:
  # Generate a random 16 character password with mixed case letters, numbers and symbols
  {{ .Values.auth.existingKey }}: {{ randAlphaNum 16 | b64enc }}
{{- end }}
