apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.clientPort }}
    targetPort: client
    protocol: TCP
    name: client
  - port: {{ .Values.service.peerPort }}
    targetPort: peer
    protocol: TCP
    name: peer
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}
---
# Servicio Headless para StatefulSet
apiVersion: v1
kind: Service
metadata:
  name: {{ include "etcd.fullname" . }}-headless
  labels:
    {{- include "etcd.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - port: {{ .Values.service.clientPort }}
    targetPort: client
    protocol: TCP
    name: client
  - port: {{ .Values.service.peerPort }}
    targetPort: peer
    protocol: TCP
    name: peer
  selector:
    {{- include "etcd.selectorLabels" . | nindent 4 }}