apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-ldap-config
data:
  ldap.yaml: |
    srvconfig:
      debug: {{ .Values.ldapConfig.debug | quote }}
      admin_password_file: {{ .Values.ldapConfig.adminpasswordfile }}
      ldap_port: {{ .Values.ldapConfig.ldapport | quote }}
      srvtls:
        ldaps_port: {{ .Values.ldapConfig.srvtls.ldapsport | quote }}
        ldaps_tls:
          ca_file: {{ .Values.ldapConfig.srvtls.ldapstls.cafile }}
          crt_file: {{ .Values.ldapConfig.srvtls.ldapstls.crtfile }}
          crt_key_file: {{ .Values.ldapConfig.srvtls.ldapstls.crtkeyfile }}
    database:
      {{- toYaml .Values.ldapConfig.database | nindent 6 }}
    schemas:
      {{- toYaml .Values.ldapConfig.schemas | nindent 6 }}
    modules:
      {{- toYaml .Values.ldapConfig.modules | nindent 6 }}
