{{- if .Values.admin.ingress.enabled -}}
{{- $fullName := include "powerdns.fullname" . -}}
{{- $svcPort := .Values.admin.service.port -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.admin.ingress.hostname }}.{{ .Values.domain }}
      http:
        paths:
          - path: {{ .Values.admin.ingress.path | quote }}
            backend:
              service:
                name: {{ $fullName }}-service-admin
                port: 
                  number: {{ $svcPort }}
            pathType: ImplementationSpecific
{{- end }}
